version: "3.4"

services:
  db:
    image: postgres:13-alpine
    volumes:
      - ../br-volume/postgres:/var/lib/postgresql/data/
    ports:
      - 6432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=inspector
      - POSTGRES_DB=pokemon-inspection

  backend:
    build: .
    command: >
      sh -c "python main.py"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
